//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnhancedInventory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnhancedInventory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear for the selected character.
        /// </summary>
        internal static string InventoryCurrentEquippedText {
            get {
                return ResourceManager.GetString("InventoryCurrentEquippedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-zero price and weight.
        /// </summary>
        internal static string InventoryNonZeroPWText {
            get {
                return ResourceManager.GetString("InventoryNonZeroPWText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price / Weight (in ascending order).
        /// </summary>
        internal static string InventoryPriceWeightAscendingText {
            get {
                return ResourceManager.GetString("InventoryPriceWeightAscendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price / Weight (in descending order).
        /// </summary>
        internal static string InventoryPriceWeightDescendingText {
            get {
                return ResourceManager.GetString("InventoryPriceWeightDescendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickslot utilities.
        /// </summary>
        internal static string InventoryQuickslotUtilitiesText {
            get {
                return ResourceManager.GetString("InventoryQuickslotUtilitiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter item name....
        /// </summary>
        internal static string InventorySearchBarText {
            get {
                return ResourceManager.GetString("InventorySearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlearned recipes.
        /// </summary>
        internal static string InventoryUnlearnedRecipesText {
            get {
                return ResourceManager.GetString("InventoryUnlearnedRecipesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlearned scrolls.
        /// </summary>
        internal static string InventoryUnlearnedScrollsText {
            get {
                return ResourceManager.GetString("InventoryUnlearnedScrollsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread documents.
        /// </summary>
        internal static string InventoryUnreadDocumentsText {
            get {
                return ResourceManager.GetString("InventoryUnreadDocumentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usable without UMD check.
        /// </summary>
        internal static string InventoryUsableWithoutUMDText {
            get {
                return ResourceManager.GetString("InventoryUsableWithoutUMDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn {0} scrolls.
        /// </summary>
        internal static string SpellbookLearnableScrollsButtonText {
            get {
                return ResourceManager.GetString("SpellbookLearnableScrollsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter spell name....
        /// </summary>
        internal static string SpellbookSearchBarText {
            get {
                return ResourceManager.GetString("SpellbookSearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortitude.
        /// </summary>
        internal static string SpellbookSearchFilterCheckKeywordFortitudeText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterCheckKeywordFortitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflex.
        /// </summary>
        internal static string SpellbookSearchFilterCheckKeywordReflexText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterCheckKeywordReflexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will.
        /// </summary>
        internal static string SpellbookSearchFilterCheckKeywordWillText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterCheckKeywordWillText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filter.
        /// </summary>
        internal static string SpellbookSearchFilterNoFilterText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterNoFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell targets {0}.
        /// </summary>
        internal static string SpellbookSearchFilterTargetsText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterTargetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all spell levels.
        /// </summary>
        internal static string SpellbookShowAllSpellLevelsCheckboxText {
            get {
                return ResourceManager.GetString("SpellbookShowAllSpellLevelsCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show metamagic.
        /// </summary>
        internal static string SpellbookShowMetamagicCheckboxText {
            get {
                return ResourceManager.GetString("SpellbookShowMetamagicCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show unlearned spells.
        /// </summary>
        internal static string SpellbookShowUnlearnedSpellsCheckboxText {
            get {
                return ResourceManager.GetString("SpellbookShowUnlearnedSpellsCheckboxText", resourceCulture);
            }
        }
    }
}
