//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnhancedInventory.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnhancedInventory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Gear for the selected character 的本地化字符串。
        /// </summary>
        internal static string InventoryCurrentEquippedText {
            get {
                return ResourceManager.GetString("InventoryCurrentEquippedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-zero price and weight 的本地化字符串。
        /// </summary>
        internal static string InventoryNonZeroPWText {
            get {
                return ResourceManager.GetString("InventoryNonZeroPWText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price / Weight (in ascending order) 的本地化字符串。
        /// </summary>
        internal static string InventoryPriceWeightAscendingText {
            get {
                return ResourceManager.GetString("InventoryPriceWeightAscendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price / Weight (in descending order) 的本地化字符串。
        /// </summary>
        internal static string InventoryPriceWeightDescendingText {
            get {
                return ResourceManager.GetString("InventoryPriceWeightDescendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quickslot utilities 的本地化字符串。
        /// </summary>
        internal static string InventoryQuickslotUtilitiesText {
            get {
                return ResourceManager.GetString("InventoryQuickslotUtilitiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter item name... 的本地化字符串。
        /// </summary>
        internal static string InventorySearchBarText {
            get {
                return ResourceManager.GetString("InventorySearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlearned recipes 的本地化字符串。
        /// </summary>
        internal static string InventoryUnlearnedRecipesText {
            get {
                return ResourceManager.GetString("InventoryUnlearnedRecipesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlearned scrolls 的本地化字符串。
        /// </summary>
        internal static string InventoryUnlearnedScrollsText {
            get {
                return ResourceManager.GetString("InventoryUnlearnedScrollsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unread documents 的本地化字符串。
        /// </summary>
        internal static string InventoryUnreadDocumentsText {
            get {
                return ResourceManager.GetString("InventoryUnreadDocumentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usable without UMD check 的本地化字符串。
        /// </summary>
        internal static string InventoryUsableWithoutUMDText {
            get {
                return ResourceManager.GetString("InventoryUsableWithoutUMDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Learn {0} scrolls 的本地化字符串。
        /// </summary>
        internal static string SpellbookLearnableScrollsButtonText {
            get {
                return ResourceManager.GetString("SpellbookLearnableScrollsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter spell name... 的本地化字符串。
        /// </summary>
        internal static string SpellbookSearchBarText {
            get {
                return ResourceManager.GetString("SpellbookSearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fortitude 的本地化字符串。
        /// </summary>
        internal static string SpellbookSearchFilterCheckKeywordFortitudeText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterCheckKeywordFortitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reflex 的本地化字符串。
        /// </summary>
        internal static string SpellbookSearchFilterCheckKeywordReflexText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterCheckKeywordReflexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will 的本地化字符串。
        /// </summary>
        internal static string SpellbookSearchFilterCheckKeywordWillText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterCheckKeywordWillText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No filter 的本地化字符串。
        /// </summary>
        internal static string SpellbookSearchFilterNoFilterText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterNoFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell targets {0} 的本地化字符串。
        /// </summary>
        internal static string SpellbookSearchFilterTargetsText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterTargetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show all spell levels 的本地化字符串。
        /// </summary>
        internal static string SpellbookShowAllSpellLevelsCheckboxText {
            get {
                return ResourceManager.GetString("SpellbookShowAllSpellLevelsCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show metamagic 的本地化字符串。
        /// </summary>
        internal static string SpellbookShowMetamagicCheckboxText {
            get {
                return ResourceManager.GetString("SpellbookShowMetamagicCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show unlearned spells 的本地化字符串。
        /// </summary>
        internal static string SpellbookShowUnlearnedSpellsCheckboxText {
            get {
                return ResourceManager.GetString("SpellbookShowUnlearnedSpellsCheckboxText", resourceCulture);
            }
        }
    }
}
