//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnhancedInventory.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnhancedInventory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Enter item name... 的本地化字符串。
        /// </summary>
        public static string InventorySearchBarText {
            get {
                return ResourceManager.GetString("InventorySearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quickslot utilities 的本地化字符串。
        /// </summary>
        public static string QuickslotUtilitiesText {
            get {
                return ResourceManager.GetString("QuickslotUtilitiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Learn {0} scrolls 的本地化字符串。
        /// </summary>
        public static string SpellbookLearnableScrollsButtonText {
            get {
                return ResourceManager.GetString("SpellbookLearnableScrollsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter spell name... 的本地化字符串。
        /// </summary>
        public static string SpellbookSearchBarText {
            get {
                return ResourceManager.GetString("SpellbookSearchBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fortitude 的本地化字符串。
        /// </summary>
        public static string SpellbookSearchFilterCheckKeywordFortitudeText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterCheckKeywordFortitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reflex 的本地化字符串。
        /// </summary>
        public static string SpellbookSearchFilterCheckKeywordReflexText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterCheckKeywordReflexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will 的本地化字符串。
        /// </summary>
        public static string SpellbookSearchFilterCheckKeywordWillText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterCheckKeywordWillText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No filter 的本地化字符串。
        /// </summary>
        public static string SpellbookSearchFilterNoFilterText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterNoFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell targets fortitude 的本地化字符串。
        /// </summary>
        public static string SpellbookSearchFilterTargetsFortitudeText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterTargetsFortitudeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell targets reflex 的本地化字符串。
        /// </summary>
        public static string SpellbookSearchFilterTargetsReflexText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterTargetsReflexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell targets will 的本地化字符串。
        /// </summary>
        public static string SpellbookSearchFilterTargetsWillText {
            get {
                return ResourceManager.GetString("SpellbookSearchFilterTargetsWillText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show metamagic 的本地化字符串。
        /// </summary>
        public static string SpellbookSearchMetamagicButtonText {
            get {
                return ResourceManager.GetString("SpellbookSearchMetamagicButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show unlearned spells 的本地化字符串。
        /// </summary>
        public static string SpellbookSearchPossibleSpellsButtonText {
            get {
                return ResourceManager.GetString("SpellbookSearchPossibleSpellsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show all spell levels 的本地化字符串。
        /// </summary>
        public static string SpellbookSearchToggleAllButtonText {
            get {
                return ResourceManager.GetString("SpellbookSearchToggleAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlearned recipes 的本地化字符串。
        /// </summary>
        public static string UnlearnedRecipesText {
            get {
                return ResourceManager.GetString("UnlearnedRecipesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlearned scrolls 的本地化字符串。
        /// </summary>
        public static string UnlearnedScrollsText {
            get {
                return ResourceManager.GetString("UnlearnedScrollsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unread documents 的本地化字符串。
        /// </summary>
        public static string UnreadDocumentsText {
            get {
                return ResourceManager.GetString("UnreadDocumentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usable without UMD check 的本地化字符串。
        /// </summary>
        public static string UsableWithoutUMDText {
            get {
                return ResourceManager.GetString("UsableWithoutUMDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price / Weight (in descending order) 的本地化字符串。
        /// </summary>
        public static string WeightValueDownText {
            get {
                return ResourceManager.GetString("WeightValueDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price / Weight (in ascending order) 的本地化字符串。
        /// </summary>
        public static string WeightValueUpText {
            get {
                return ResourceManager.GetString("WeightValueUpText", resourceCulture);
            }
        }
    }
}
